<?php

use Krystal\Form\Widget\BooleanWidget;
use Krystal\Form\HtmlHelper;
use Krystal\Form\Element;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Pages:Admin:Page@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new page'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>

		 <?php if (!empty($pages)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Pages:Admin:Page@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Pages:Admin:Page@deleteAction'); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadBlock('items-per-page', array('caption' => 'Pages')); ?>

<form action="<?php echo $this->url('Pages:Admin:Browser@filterAction', null); ?>">

	<div class="table-responsive">
		<table class="table table-striped table-hover table-bordered table-condensed">
			<thead>
				<tr>
					<th class="text-center">
						<?php if (!empty($pages)): ?>
						<input type="checkbox" />
						<?php endif; ?>
					</th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('id'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('id'); ?>"><i class="<?php echo $filter->isSortedByDesc('id') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> #</a>
					</th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('title'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('title'); ?>"><i class="<?php echo $filter->isSortedByDesc('title') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('Title'); ?></a>
					</th>
					<th class="text-center"><?php $this->show('Default'); ?></th>
					<th class="text-center">
						<a <?php echo HtmlHelper::addClassOnDemand($filter->isSortedBy('seo'), 'text-info'); ?> href="<?php echo $filter->getColumnSortingUrl('seo'); ?>"><i class="<?php echo $filter->isSortedByDesc('seo') ? 'glyphicon glyphicon-arrow-down': 'glyphicon glyphicon-arrow-up'; ?>"></i> <?php $this->show('SEO'); ?></a>
					</th>
					<th class="text-center"><?php $this->show('Actions'); ?></th>
				</tr>
				<tr>
					<td></td>
					<td class="col-lg-1">
						<?php echo Element::number($filter->getElementName('id'), $filter->get('id'), array('class' => 'form-control')); ?>
					</td>
					<td>
                        <?php echo Element::text($filter->getElementName('title'), $filter->get('title'), array('class' => 'form-control')); ?>
					</td>
					<td></td>
					<td class="col-lg-1">
						<?php echo BooleanWidget::render(array('class' => 'form-control', 'name' => $filter->getElementName('seo')), $filter->get('seo'), $this->getTranslator()); ?>
					</td>
					<td></td>
					<td></td>
				</tr>
			</thead>
			
			<?php if (!empty($pages)): ?>
			<tbody>
				<?php foreach ($pages as $page): ?>
				<tr>
					<td class="text-center">
						<?php if (!(!$extendedMode && $page->getProtected())): ?>
						<input type="checkbox" name="toDelete[<?php echo $page->getId(); ?>]" />
						<?php endif; ?>
					</td>
					<td class="text-center text-muted"><?php echo $page->getId(); ?></td>
					<td class="text-center"><?php echo $page->getTitle(); ?></td>
					<td class="text-center">
                        <?php echo Element::radio('default', $page->getId(), $page->isDefault()); ?>
					</td>
					<td class="text-center">
                        <?php echo Element::checkbox(sprintf('seo[%s]', $page->getId()), $page->getSeo()); ?>
					</td>
					<td class="text-center">
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('View this page on site'); ?>" data-button="view" target="_blank" href="<?php echo $page->getUrl(); ?>"><i class="glyphicon glyphicon-search"></i></a>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this page'); ?>" data-button="edit" href="<?php echo $this->url('Pages:Admin:Page@editAction', $page->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>
						
						<?php if ($extendedMode || !($page->isDefault() || $page->getProtected())): ?>
						<a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this page'); ?>" data-button="delete" data-category="main" data-id="<?php echo $page->getId(); ?>" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
						<?php endif; ?>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
			<?php endif; ?>
		</table>
		
		<br />
		
		<?php if (!empty($pages)): ?>
		<div>
			<?php if ($filter->isApplied()): ?>
			<a href="<?php echo $this->url('Pages:Admin:Browser@indexAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i> <?php $this->show('Reset filter'); ?></a>
			<?php endif; ?>
			<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-filter"></i> <?php $this->show('Filter'); ?></button>
		</div>
		<?php endif; ?>
		
		<?php if (empty($pages)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No pages'); ?></h2>
		</div>
		<?php endif; ?>
		
	</div>
</form>

<?php $this->loadBlock('paginator'); ?>
