<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<form autocomplete="off">
    <div class="btn-toolbar">
        <div class="btn-group mr-2">
            <?php $this->loadPartial('menu', array(
                'items' => array(
                    'Pages:Admin:Page@addAction' => 'Add new page',
                ),
                'actions' => array(
                    'data' => $pages,
                    'save' => 'Pages:Admin:Page@tweakAction',
                    'delete' => 'Pages:Admin:Page@deleteAction'
                )
            )); ?>
        </div>

        <?php if ($filterApplied): ?>
        <div class="btn-group mr-2">
            <a href="<?php echo $this->url('Pages:Admin:Browser@indexAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i> <?php $this->show('Reset filter'); ?></a>
        </div>
        <?php endif; ?>

        <div class="btn-group mr-2">
            <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i> <?php $this->show('Filter'); ?></button>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <?php $this->loadPartial('items-per-page', array('caption' => 'Pages')); ?>
        </div>


        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($pages, array(
                'pk' => 'id',
                'batch' => true,
                'tableClass' => 'table table-hover table-bordered table-striped table-sm',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#',
                        'attributes' => array(
                            'class' => 'text-center text-muted'
                        )
                    ),

                    array(
                        'column' => 'name',
                        'type' => 'text',
                        'attributes' => array(
                            'class' => null
                        ),
                        'filter' => true
                    ),

                    array(
                        'column' => 'seo',
                        'label' => 'SEO',
                        'type' => 'select',
                        'value' => function($row){
                            return Element::checkbox(sprintf('seo[%s]', $row['id']), $row['seo']);
                        },
                        'filter' => $this->translateArray([
                            '0' => 'No',
                            '1' => 'Yes'
                        ])
                    ),

                    array(
                        'column' => 'default',
                        'value' => function($page){
                            return Element::radio('default', $page->getId(), $page->isDefault());
                        }
                    )
                ),

                'actions' => array(
                    'view' => function($page){
                        return Icon::view($page->getUrl(), $this->translate('View this page on site'));
                    },

                    'edit' => function($page){
                        return Icon::edit(
                            $this->url('Pages:Admin:Page@editAction', $page->getId()),
                            $this->translate('Edit this page')
                        );
                    },

                    'remove' => function($page) use ($extendedMode){
                        if ($extendedMode || !($page->isDefault() || $page->getProtected())) {
                            return Icon::remove(
                                $this->url('Pages:Admin:Page@deleteAction', $page->getId()), 
                                $this->translate('Remove this page')
                            );
                        } else {
                            return null;
                        }
                    }
                )

            ))); ?>

            <br />

            <?php if (empty($pages)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No pages'); ?></h2>
            </div>
            <?php endif; ?>
        </div>

        <?php $this->loadPartial('paginator'); ?>
    </div>
</form>

