<?php

use Krystal\Form\Element;
use Krystal\Widget\GridWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Pages:Admin:Page@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new page'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>

		 <?php if (!empty($pages)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Pages:Admin:Page@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Pages:Admin:Page@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Pages')); ?>

<form action="<?php echo $this->url('Pages:Admin:Browser@filterAction', null); ?>" autocomplete="off">
    <div class="table-responsive">
        <?= $this->widget(new GridWidget($pages, array(
            // A column to be considered as a primary key
            'pk' => 'id',
            'batch' => true,
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name',
                    'type' => 'text',
                    'filter' => true
                ),

                array(
                    'column' => 'seo',
                    'label' => 'SEO',
                    'type' => 'select',
                    'value' => function($row){
                        return Element::checkbox(sprintf('seo[%s]', $row['id']), $row['seo']);
                    },
                    'filter' => $this->translateArray([
                        '0' => 'No',
                        '1' => 'Yes'
                    ])
                ),

                array(
                    'column' => 'default',
                    'value' => function($page){
                        return Element::radio('default', $page->getId(), $page->isDefault());
                    }
                )
            ),

            'actions' => array(
                'view' => function($page){
                    return Icon::view($page->getUrl(), $this->translate('View this page on site'));
                },

                'edit' => function($page){
                    return Icon::edit(
                        $this->url('Pages:Admin:Page@editAction', $page->getId()),
                        $this->translate('Edit this page')
                    );
                },

                'remove' => function($page) use ($extendedMode){
                    if ($extendedMode || !($page->isDefault() || $page->getProtected())) {
                        return Icon::remove(
                            $this->url('Pages:Admin:Page@deleteAction', $page->getId()), 
                            $this->translate('Remove this page')
                        );
                    } else {
                        return null;
                    }
                }
            )

        ), $route)); ?>

		<br />

		<?php if (!empty($pages)): ?>
		<div>
			<?php if ($filterApplied): ?>
			<a href="<?php echo $this->url('Pages:Admin:Browser@indexAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-trash"></i> <?php $this->show('Reset filter'); ?></a>
			<?php endif; ?>
			<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-filter"></i> <?php $this->show('Filter'); ?></button>
		</div>
		<?php endif; ?>

		<?php if (empty($pages)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No pages'); ?></h2>
		</div>
		<?php endif; ?>

	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
