<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form data-group="page">
	<ul class="nav nav-tabs" role="tablist">
		<li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Page'); ?></a></li>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
	</ul>

	<div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
            <div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $page); ?>

                    <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                        <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Page name'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][content]', $language->getId()), $entity->getContent(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="options">
                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <?php echo Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this page. By default is taken from a title'))); ?>
                                        <span class="input-group-addon">
                                            <a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <?php echo Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Page title'))); ?>
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                                <div class="col-lg-10">
                                    <?php echo Element::textarea(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                                <div class="col-lg-10">
                                    <?php echo Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
			</div>
		</div>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <div class="well">
                <?php echo Element::hidden('page[id]', $entity->getId()); ?>
                <?php echo Element::hidden('page[image]', $entity->getImage()); ?>

                <?php if (!$extendedMode): ?>
                <div class="hidden">
                <?php endif; ?>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Controller'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('page[controller]', $controllers, $entity->getController(), array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Template override'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('page[template]', $entity->getTemplate(), array('class' => 'form-control', 'placeholder' => $this->translate('If you need another template which is different from default one, you can define its name here'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Protect'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('page[protected]', $entity->getProtected(), array('class' => 'form-control', 'title' => $this->translate('If you protect the page you are going to created, them users that use only simple mode will not be able to remove it'))); ?>
                    </div>
                </div>

                <?php if (!$extendedMode): ?>
                </div>
                <?php endif; ?>

                <?php if ($new): ?>
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Make default'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('page[makeDefault]', $entity->getProtected(), array('class' => 'form-control', 'title' => $this->translate('Whether it should be home page or not'))); ?>
                    </div>
                </div>
                <?php endif; ?>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('page[seo]', $entity->getSeo(), array('class' => 'form-control')); ?>
                    </div>
                </div>

                <div class="form-group">
					<label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
					<div class="col-lg-10">

                        <?php if ($entity->hasImage()): ?>
                        <p><img class="img-responsive" src="<?php echo $entity->getImageUrl('350x350'); ?>" /></p>
                        <p>
                            <label for="removeCover"><?php $this->show('Remove this cover'); ?>&nbsp;</label>
                            <input type="checkbox" id="removeCover" name="page[remove_cover]" data-toggle="tooltip" data-placement="left" title="<?php $this->show('Check it if you want to remove this cover'); ?>" />
                        </p>

						<?php else: ?>
                        <p><img data-image="preview" /></p>

                        <?php endif; ?>

                        <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Upload a file'); ?></a>
                        <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden', 'data-plugin' => 'preview')); ?>
					</div>
				</div>
            </div>
        </div>
	</div>

    <?php if ($new): ?>
    <button data-button="add" data-back-url="<?php echo $this->url('Pages:Admin:Page@editAction', null); ?>" data-url="<?php echo $this->url('Pages:Admin:Page@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
    <button data-button="add-create" data-url="<?php echo $this->url('Pages:Admin:Page@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>

    <?php else: ?>
    <button data-button="save" data-url="<?php echo $this->url('Pages:Admin:Page@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-button="save-create" data-back-url="<?php echo $this->url('Pages:Admin:Page@addAction'); ?>" data-url="<?php echo $this->url('Pages:Admin:Page@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>

    <?php endif; ?>

    <button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
    <button data-button="cancel" data-url="<?php echo $this->url('Pages:Admin:Browser@indexAction'); ?>" type="button" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>
